# Copyright 2018 M. Riechert and D. Meyer. Licensed under the MIT License.

image: Visual Studio 2017 # See https://www.appveyor.com/docs/build-environment/

clone_depth: 50

environment:
  global:
    BUILD_SYSTEM: CMake

  matrix:
    - BUILD_TYPE: Debug
      CC: gcc
      FC: gfortran
      MODE: serial
      NESTING: basic
      GRIB1: 0
      GRIB2: 1
      
    - BUILD_TYPE: Debug
      CC: gcc
      FC: gfortran
      MODE: dmpar
      NESTING: basic
      GRIB1: 0
      GRIB2: 1

install:
  - ps: .ci\appveyor\dump-vm-specs.ps1
  - ps: .ci\appveyor\increase-pagefile-size.ps1
  - call .ci\appveyor\setup-dependencies.bat
  - ps: .ci\appveyor\dump-vm-specs.ps1

build_script:
  - call .ci\appveyor\install-wrf.bat
