# WRF-CMake (https://github.com/WRF-CMake/WRF).
# Copyright 2018 M. Riechert and D. Meyer. Licensed under the MIT License.

image: Visual Studio 2017 # See https://www.appveyor.com/docs/build-environment/

clone_depth: 50

skip_commits:
  files:
    - 'doc/*'
    - 'README*'

environment:
  global:
    BUILD_SYSTEM: CMake

  matrix:
    - BUILD_TYPE: Debug
      CC: gcc
      FC: gfortran
      MODE: serial
      NESTING: basic
      GRIB1: 0
      GRIB2: 1
      
    - BUILD_TYPE: Debug
      CC: gcc
      FC: gfortran
      MODE: dmpar
      NESTING: basic
      GRIB1: 0
      GRIB2: 1

install:
  - ps: .ci\windows\dump-vm-specs.ps1
  - call .ci\windows\setup-dependencies.bat

build_script:
  - call .ci\windows\install-wrf.bat
