# WRF-CMake (https://github.com/WRF-CMake/wrf).
# Copyright 2018 M. Riechert and D. Meyer. Licensed under the MIT License.

language: python
python: "3.6"

jobs:
  include:
    # Make builds
    
    - stage: build
      os: linux
      dist: trusty
      sudo: required
      env:
        - BUILD_SYSTEM=Make
        - BUILD_TYPE=Debug
        - CC=gcc
        - FC=gfortran
        - MODE=serial
        - REAL8=0

    - stage: build
      os: linux
      dist: trusty
      sudo: required
      env:
        - BUILD_SYSTEM=Make
        - BUILD_TYPE=Debug
        - CC=gcc
        - FC=gfortran
        - MODE=dm_sm
        - REAL8=1

    - stage: build
      os: linux
      dist: xenial
      sudo: required
      env:
        - BUILD_SYSTEM=Make
        - BUILD_TYPE=Debug
        - CC=gcc-9
        - FC=gfortran-9
        - MODE=serial
        - REAL8=1

    - stage: build
      os: linux
      dist: xenial
      sudo: required
      env:
        - BUILD_SYSTEM=Make
        - BUILD_TYPE=Debug
        - CC=gcc-9
        - FC=gfortran-9
        - MODE=dm_sm
        - REAL8=0
    
    - stage: build
      os: osx
      osx_image: xcode10
      language: generic
      env:
        - BUILD_SYSTEM=Make
        - BUILD_TYPE=Debug
        - CC=gcc-9 # GNU via Homebrew
        - FC=gfortran-9
        - MODE=serial
        - REAL8=1

    - stage: build
      os: osx
      osx_image: xcode10
      language: generic
      env:
        - BUILD_SYSTEM=Make
        - BUILD_TYPE=Debug
        - CC=gcc-9 # GNU via Homebrew
        - FC=gfortran-9
        - MODE=dm_sm
        - REAL8=0

    # CMake builds

    - stage: build
      os: linux
      dist: trusty
      sudo: required # Need sudo to install netcdf via apt as not whitelisted 
      env:
        - BUILD_SYSTEM=CMake
        - BUILD_TYPE=Debug
        - CC=gcc
        - FC=gfortran
        - GRIB1=0
        - GRIB2=1
        - MODE=serial
        - NESTING=basic
        - REAL8=1

    - stage: build
      os: linux
      dist: trusty
      sudo: required
      env:
        - BUILD_SYSTEM=CMake
        - BUILD_TYPE=Debug
        - CC=gcc
        - FC=gfortran
        - GRIB1=1
        - GRIB2=0
        - MODE=dm_sm
        - NESTING=basic
        - REAL8=0

    - stage: build
      os: linux
      dist: xenial
      sudo: required # Need sudo to install netcdf via apt as not whitelisted 
      env:
        - BUILD_SYSTEM=CMake
        - BUILD_TYPE=Debug
        - CC=gcc-9
        - FC=gfortran-9
        - GRIB1=0
        - GRIB2=1
        - MODE=serial
        - NESTING=basic
        - REAL8=0

    - stage: build
      os: linux
      dist: xenial
      sudo: required
      env:
        - BUILD_SYSTEM=CMake
        - BUILD_TYPE=Debug
        - CC=gcc-9
        - FC=gfortran-9
        - GRIB1=1
        - GRIB2=0
        - MODE=dm_sm
        - NESTING=basic
        - REAL8=1

    - stage: build
      os: osx
      osx_image: xcode10
      language: generic
      env:
        - BUILD_SYSTEM=CMake
        - BUILD_TYPE=Debug
        - CC=gcc-9 # GNU via Homebrew
        - FC=gfortran-9
        - GRIB1=1
        - GRIB2=1
        - MODE=serial
        - NESTING=basic
        - REAL8=0

    - stage: build
      os: osx
      osx_image: xcode10
      language: generic
      env:
        - BUILD_SYSTEM=CMake
        - BUILD_TYPE=Debug
        - CC=clang # Apple Clang
        - FC=gfortran-9
        - GRIB1=1
        - GRIB2=1
        - MODE=dmpar # not using dm_sm as Apple's Clang doesn't easily support OpenMP
        - NESTING=basic
        - REAL8=1

before_install:
  - .ci/unix/dump-vm-specs.sh
  - .ci/unix/setup-dependencies.sh

install:
  - .ci/unix/install-wrf.sh

script: skip
