trigger:
- wrf-cmake

jobs:
- template: .ci/azure-pipelines/matrix.yml
  parameters:
    BUILD_TYPES: [Debug]
    #MODES: [dm_sm]
    MODES: [serial]
    WATS_DIFF: false
    WATS_PLOTS: true # TODO disable