# Run manually or by schedule only.
trigger: none
pr: none

jobs:
- template: .ci/azure-pipelines/matrix.yml
  parameters:
    BUILD_TYPES: [Debug, Release]
    MODES: [serial, smpar, dmpar, dm_sm]
    WATS_PLOTS: true
