trigger:
- wrf-cmake

jobs:
- job: windows_make
  displayName: Windows (Make)
  pool:
    vmImage: vs2017-win2016
  variables:
    SYSTEM: make
    BUILD_TYPE: Debug
    MODE: serial
  steps:
  - template: .ci/azure/windows.yml

- job: windows_cmake
  displayName: Windows (CMake)
  pool:
    vmImage: vs2017-win2016
  variables:
    SYSTEM: cmake
    BUILD_TYPE: Debug
    MODE: serial
    GRIB1: 0
    GRIB2: 1
    NESTING: basic
  steps:
  - template: .ci/azure/windows.yml

# TODO CC/FC are not used for Make builds

- job: ubuntu_make
  displayName: Ubuntu (Make)
  pool:
    vmImage: ubuntu-16.04
  variables:
    OS_NAME: linux
    SYSTEM: make
    BUILD_TYPE: Debug
    CC: gcc
    FC: gfortran
    MODE: serial
  steps:
  - template: .ci/azure/ubuntu.yml

- job: ubuntu_cmake
  displayName: Ubuntu (CMake)
  pool:
    vmImage: ubuntu-16.04
  variables:
    OS_NAME: linux
    SYSTEM: cmake
    BUILD_TYPE: Debug
    CC: gcc
    FC: gfortran
    MODE: serial
    GRIB1: 0
    GRIB2: 1
    NESTING: basic
  steps:
  - template: .ci/azure/ubuntu.yml

- job: macos_make
  displayName: macOS (Make)
  pool:
    vmImage: macos-10.13
  variables:
    OS_NAME: osx
    SYSTEM: make
    BUILD_TYPE: Debug
    CC: gcc-8
    FC: gfortran-8
    MODE: serial
  steps:
  - template: .ci/azure/macos.yml

- job: macos_cmake
  displayName: macOS (CMake)
  pool:
    vmImage: macos-10.13
  variables:
    OS_NAME: osx
    SYSTEM: cmake
    BUILD_TYPE: Debug
    CC: gcc-8
    FC: gfortran-8
    MODE: serial
    GRIB1: 0
    GRIB2: 1
    NESTING: basic
  steps:
  - template: .ci/azure/macos.yml