# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- wrf-cmake

jobs:
- job: windows_make
  displayName: Windows (Make)
  pool:
    vmImage: vs2017-win2016
  steps:
  - script: |
      echo ##vso[task.setvariable variable=SYSTEM]make
      echo ##vso[task.setvariable variable=BUILD_TYPE]Debug
      echo ##vso[task.setvariable variable=MODE]serial
  - template: .ci/azure/windows.yml

- job: ubuntu_make
  displayName: Ubuntu (Make)
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: |
      echo ##vso[task.setvariable variable=OS_NAME]linux
      echo ##vso[task.setvariable variable=SYSTEM]make
      echo ##vso[task.setvariable variable=BUILD_TYPE]Debug
      echo ##vso[task.setvariable variable=CC]gcc
      echo ##vso[task.setvariable variable=FC]gfortran
      echo ##vso[task.setvariable variable=MODE]serial
  - template: .ci/azure/ubuntu.yml

- job: macos_make
  displayName: macOS (Make)
  pool:
    vmImage: macos-10.13
  steps:
  - script: |
      echo ##vso[task.setvariable variable=OS_NAME]osx
      echo ##vso[task.setvariable variable=SYSTEM]make
      echo ##vso[task.setvariable variable=BUILD_TYPE]Debug
      echo ##vso[task.setvariable variable=CC]gcc-8
      echo ##vso[task.setvariable variable=FC]gfortran-8
      echo ##vso[task.setvariable variable=MODE]serial
  - template: .ci/azure/macOS.yml