# Runs on commits to the wrf-cmake branch and PRs.
trigger:
- wrf-cmake

jobs:
- template: .ci/azure-pipelines/matrix.yml
  parameters:
    BUILD_TYPES: [Debug, Release]
    MODES: [serial, smpar, dmpar, dm_sm]
    WATS_DIFF: false
    WATS_PLOTS: true
