trigger:
- wrf-cmake

variables:
  WPS_REPO: WRF-CMake/WPS
  WPS_COMMIT: letmaik/azure-pipelines
  WATS_REPO: WRF-CMake/wats
  WATS_BRANCH: master
  WATS_MODE: wrf
  WATS_WPS_PKG_VERSION: 0.0.2

jobs:
- template: .ci/azure-pipelines/matrix.yml
