# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- wrf-cmake

jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - script: echo "##vso[task.setvariable variable=SYSTEM]make"
  - template: .ci/azure/windows.yml

- job: Ubuntu
  pool:
    vmImage: ubuntu-16.04
  steps:
  - script: echo "##vso[task.setvariable variable=OS_NAME]linux"
  - script: echo "##vso[task.setvariable variable=SYSTEM]make"
  - template: ci/azure/ubuntu.yml

- job: macOS
  pool:
    vmImage: macos-10.13
  steps:
  - script: echo "##vso[task.setvariable variable=OS_NAME]osx"
  - script: echo "##vso[task.setvariable variable=SYSTEM]make"
  - template: ci/azure/macos.yml