# WRF-CMake (https://github.com/WRF-CMake/wrf).
# Copyright 2019 M. Riechert and D. Meyer. Licensed under the MIT License.

jobs:
- job: ${{ parameters.OS_NAME }}_${{ parameters.BUILD_SYSTEM }}_${{ parameters.BUILD_TYPE }}_${{ parameters.MODE }}
  displayName: '${{ parameters.OS_NAME }} ${{ parameters.BUILD_SYSTEM }}: ${{ parameters.BUILD_TYPE }}, ${{ parameters.MODE }}'

  timeoutInMinutes: 0

  pool:
    ${{ if or(eq(parameters.OS_NAME, 'Ubuntu'), eq(parameters.OS_NAME, 'CentOS')) }}:
      vmImage: ubuntu-latest
    ${{ if eq(parameters.OS_NAME, 'macOS') }}:
      vmImage: macOS-11

  variables:
    ${{ insert }}: ${{ parameters }}
    ${{ if eq(parameters.OS_NAME, 'Ubuntu') }}:
      IMAGE: ubuntu:20.04
      run: .ci/unix/run-in-docker.sh
    ${{ if eq(parameters.OS_NAME, 'CentOS') }}:
      IMAGE: quay.io/pypa/manylinux2014_x86_64:latest
      run: .ci/unix/run-in-docker.sh
    ${{ if eq(parameters.OS_NAME, 'macOS') }}:
      run: ''
        
  steps:
  - script: .ci/unix/increase-swap-space.sh
    displayName: Increase swap space
  
  - script: $(run) .ci/unix/dump-vm-specs.sh
    displayName: Dump VM specs

  - script: $(run) printenv | sort
    displayName: Dump environment variables

  - script: $(run) .ci/unix/setup-dependencies.sh
    displayName: Setup dependencies

  - script: $(run) .ci/unix/install-wrf.sh
    displayName: Install WRF

  - ${{ if eq(parameters.WATS_RUN, 'true') }}:
    - template: wats_run.yml

  - ${{ if eq(parameters.RELEASE, 'true') }}:
    - template: release.yml
      parameters:
        ${{ insert }}: ${{ parameters }}
