jobs:
- job: ${{ parameters.OS_NAME }}_${{ parameters.BUILD_SYSTEM }}_${{ parameters.BUILD_TYPE }}_${{ parameters.MODE }}
  displayName: '${{ parameters.OS_NAME }} ${{ parameters.BUILD_SYSTEM }}: ${{ parameters.BUILD_TYPE }}, ${{ parameters.MODE }}'

  timeoutInMinutes: 0

  pool:
    ${{ if eq(parameters.OS_NAME, 'Linux') }}:
      vmImage: ubuntu-16.04
    ${{ if eq(parameters.OS_NAME, 'macOS') }}:
      vmImage: macos-10.13

  variables:
    ${{ insert }}: ${{ parameters }}

  steps:
  #- ${{ if eq(parameters.OS_NAME, 'macOS') }}:
  #  # See https://stackoverflow.com/questions/23112515/mpich2-gethostbyname-failed.
  #  # (occured randomly)
  #  # The below breaks pipelines, see https://github.com/microsoft/azure-pipelines-image-generation/issues/932.
  #  - script: |
  #      echo "127.0.0.1 $(sudo scutil --get LocalHostName).local" | sudo tee -a /etc/hosts
  #    displayName: Fix hostname

  - script: .ci/unix/dump-vm-specs.sh
    displayName: Dump VM specs

  - script: printenv
    displayName: Dump environment variables

  - script: .ci/unix/setup-dependencies.sh
    displayName: Setup dependencies

  - script: .ci/unix/install-wrf.sh
    displayName: Install WRF

  - ${{ if eq(parameters.WATS_RUN, 'true') }}:
    - template: wats_run.yml
