# WRF-CMake (https://github.com/WRF-CMake/wrf).
# Copyright 2019 M. Riechert and D. Meyer. Licensed under the MIT License.

steps:
- bash: $(run) .ci/unix/use-conda.sh
  displayName: Enable Conda

- bash: $(run) .ci/unix/install-wats.sh
  displayName: Install WATS

- task: UniversalPackages@0
  displayName: Download WPS outputs
  inputs:
    command: download
    downloadDirectory: wats_wps_outputs/
    vstsFeed: WATS
    vstsFeedPackage: wps.ref
    vstsPackageVersion: $(WATS_WPS_PKG_VERSION)

- bash: |
    cd wats_wps_outputs
    find . -type f
  displayName: List WPS output files

- bash: $(run) .ci/unix/run-wats.sh
  displayName: Run WATS

- task: PublishBuildArtifacts@1
  displayName: Store WATS outputs
  inputs:
    pathtoPublish: wats_work/output
    artifactName: wats_$(OS_NAME)_$(BUILD_SYSTEM)_$(BUILD_TYPE)_$(MODE)
