parameters:
  OS_NAMES: [Linux, macOS, Windows]
  BUILD_SYSTEMS: [Make, CMake]
  BUILD_TYPES: [Debug, Release]
  MODES: [serial, dmpar]

jobs:
# TODO CC/FC are not used for Make builds

- ${{ each OS_NAME in parameters.OS_NAMES }}:
  - ${{ each BUILD_TYPE in parameters.BUILD_TYPES }}:
    - ${{ each MODE in parameters.MODES }}:
      - ${{ each BUILD_SYSTEM in parameters.BUILD_SYSTEMS }}:
        - ${{ if eq(parameters.OS_NAME, 'Windows') }}:
            template: .ci/azure/windows.yml
          ${{ if ne(parameters.OS_NAME, 'Windows') }}:
            template: .ci/azure/unix.yml
          parameters:
            OS_NAME: ${{ OS_NAME }}
            BUILD_SYSTEM: ${{ BUILD_SYSTEM }}
            BUILD_TYPE: ${{ BUILD_TYPE }}
            CC: gcc
            FC: gfortran
            MODE: ${{ MODE }}
      - template: .ci/azure/wats_diff.yml
        parameters:
          ${{ if eq(parameters.OS_NAME, 'Windows') }}:
            OS_NAME_MAKE: Linux
          ${{ if ne(parameters.OS_NAME, 'Windows') }}:
            OS_NAME_MAKE: ${{ OS_NAME }}
          OS_NAME_CMAKE: ${{ OS_NAME }}
          MODE: ${{ MODE }}
          BUILD_TYPE: ${{ BUILD_TYPE }}
