jobs:
- job: ${{ parameters.OS_NAME }}_${{ parameters.BUILD_SYSTEM }}_${{ parameters.BUILD_TYPE }}_${{ parameters.MODE }}
  displayName: '${{ parameters.OS_NAME }} ${{ parameters.BUILD_SYSTEM }}: ${{ parameters.BUILD_TYPE }}, ${{ parameters.MODE }}'

  timeoutInMinutes: 0

  pool:
    ${{ if eq(parameters.OS_NAME, 'Linux') }}:
      vmImage: ubuntu-16.04
    ${{ if eq(parameters.OS_NAME, 'macOS') }}:
      vmImage: macos-10.13

  variables:
    ${{ each pair in parameters }}:
      ${{ pair.key }}: ${{ pair.value }}

  steps:
  - script: |
      if [[ $OS_NAME == 'macOS' ]]; then
        sw_vers
        top -l 1 -s 0 | grep PhysMem
        sysctl hw
        df -h
      else
        lsb_release -a
        free -m
        lscpu
        df -h --total
      fi
    displayName: Dump VM specs

  - script: printenv
    displayName: Dump environment variables

  - script: .ci/azure/scripts/setup-dependencies.sh
    displayName: Install dependencies

  - script: .ci/azure/scripts/install-wrf.sh
    displayName: Install WRF

  # In Azure Pipeline builds, the repository folder is not named after the repository name.
  # When building WPS in the Make variant, WPS looks for hard-coded folder names of WRF.
  # To make WPS happy but also to avoid having to pass a different folder to the CMake config,
  # we symlink the repository to the "WRF" folder.
  - script: ln -sf `pwd` ../WRF
    displayName: Symlink repository as "WRF" for convenience

  - script: |
      set -e
      cd ..
      git clone --depth=100 --no-single-branch https://github.com/$WPS_REPO.git WPS
      cd WPS
      git checkout $WPS_COMMIT
      git log --oneline -n 1
    displayName: Download WPS

  - script: ../WPS/.ci/azure/scripts/install-wps.sh
    displayName: Install WPS

  - template: wats_run.yml
